export const PRODUCER_IS_FETCHING_DATA = 'producer/IS_FETCHING_DATA'
export const PRODUCER_FETCH_DATA_SUCCESS = 'producer/FETCH_DATA_SUCCESS'
export const PRODUCER_FETCH_HAS_ERRORED = 'producer/FETCH_HAS_ERRORED'
