export const LOCATION_IS_FETCHING_DATA = 'location/IS_FETCHING_DATA'
export const LOCATION_FETCH_DATA_SUCCESS = 'location/FETCH_DATA_SUCCESS'
export const LOCATION_FETCH_HAS_ERRORED = 'location/FETCH_HAS_ERRORED'
