export const CONTACT_PATH = '/contact'
export const PRODUCER_PATH = '/producer'
export const PRODUCERS_PATH = '/producers'
export const CREATE_PRODUCERS_PATH = '/admin/producers/create'
export const EDIT_PRODUCERS_ROUTE_PATH = '/admin/producers/edit/:userId'
export const EDIT_PRODUCERS_PATH = '/admin/producers/edit'
