export const USER_AUTHENTICATION_REQUESTED = 'user/authentication/AUTHENTICATION_REQUESTED'
export const USER_AUTHENTICATION_FAILED = 'user/authentication/AUTHENTICATION_FAILED'
export const USER_AUTHENTICATION_SUCCEEDED = 'user/authentication/AUTHENTICATION_SUCCEEDED'
