export const LOCATION_IS_LOADING = 'user/location/IS_LOADING'
export const LOCATION_HAS_ERRORED = 'user/location/HAS_ERRORED'
export const LOCATION_GET_POSITION_SUCCESS = 'user/location/GET_POSITION_SUCCESS'
export const LOCATION_GET_ADDRESS_FROM_LAT_LNG_SUCCESS = 'user/location/GET_ADDRESS_FROM_LAT_LNG_SUCCESS'
