export const PRODUCERS_IS_FETCHING_DATA = 'producers/IS_FETCHING_DATA'
export const PRODUCERS_FETCH_DATA_SUCCESS = 'producers/FETCH_DATA_SUCCESS'
export const PRODUCERS_FETCH_HAS_ERRORED = 'producers/FETCH_HAS_ERRORED'
