export const PRODUCERS_FETCH_DATA_REQUESTED = 'producers/FETCH_DATA_REQUESTED'
export const PRODUCERS_FETCH_DATA_SUCCEEDED = 'producers/FETCH_DATA_SUCCEEDED'
export const PRODUCERS_FETCH_DATA_FAILED = 'producers/FETCH_DATA_FAILED'
