export const CATEGORIES_IS_FETCHING_DATA = 'categories/IS_FETCHING_DATA'
export const CATEGORIES_FETCH_DATA_SUCCESS = 'categories/FETCH_DATA_SUCCESS'
export const CATEGORIES_FETCH_DATA_HAS_ERRORED = 'categories/FETCH_DATA_HAS_ERRORED'
