export const CREATE_PRODUCER_REQUESTED = 'admin/CREATE_PRODUCER_REQUESTED'
export const CREATE_PRODUCER_SUCCEEDED = 'admin/CREATE_PRODUCER_SUCCEEDED'
export const CREATE_PRODUCER_HAS_ERRORED = 'admin/CREATE_PRODUCER_HAS_ERRORED'
